### ISSUE TITLE
Add x86 releases

### ISSUE THREAD

**Issue by piegit** [Syroot/CafiineServer#2]
I have an x86 processor running windows 10

**Comment by RayKoopa** [comment]
I need a lot more details or I can't help. Which release did you try, and what is the exact error message. If in doubt, send a screenshot of the error message.

**Comment by RayKoopa** [comment]
At the moment, there is no x86 release. Those might be added later, but this is not a priority. Maybe 0.8.0.0 is compiled for x86, try that version instead, or compile an x86 version from source.

**Comment by piegit** [comment]
yep 0.8.0.0 is for x86

**Comment by RayKoopa** [comment]
Using that version would be a good workaround for now. There's not really anything missing from it compared to 1.0.0.0.
Right now, the toolset used for 1.0.0.0 is going through several 3rd party changes making it a little untrivial to compile it for x86, but that will be added as soon it's clear on how to use it.

**Comment by RayKoopa** [comment]
An x86 release has been added, though the build is not automated yet.
Good enough due to how unfinished and buggy the .NET Core tooling is at the moment.
